"""Four-dimensional locomotion command generated by Isaac Lab's Command Manager."""

from __future__ import annotations

import math
from collections.abc import Sequence

import torch

from isaaclab.managers import CommandTerm, CommandTermCfg
from isaaclab.utils.configclass import configclass


LOCOMOTION_COMMAND_NAME = "locomotion"
LOCOMOTION_COMMAND_DIM = 4
FORWARD = 0
LATERAL = 1
YAW_RATE = 2
BODY_HEIGHT = 3


class LocomotionCommand(CommandTerm):
    """Sample and shape body-frame velocity and body-height commands."""

    cfg: LocomotionCommandCfg

    def __init__(self, cfg: LocomotionCommandCfg, env) -> None:
        super().__init__(cfg, env)
        self._validate_cfg()
        self._command = torch.zeros(
            (self.num_envs, LOCOMOTION_COMMAND_DIM), device=self.device
        )
        self._target_command = torch.zeros_like(self._command)
        self._max_rate = torch.tensor(cfg.max_rate, device=self.device)
        self.cfg.cmd_kind = self.cfg.cmd_kind or "command/body/locomotion"
        self.cfg.element_names = self.cfg.element_names or [
            "velocity_forward_mps",
            "velocity_lateral_mps",
            "yaw_rate_radps",
            "body_height_m",
        ]

    @property
    def command(self) -> torch.Tensor:
        """Return the shaped command consumed by both observations and rewards."""
        return self._command

    @property
    def raw_command(self) -> torch.Tensor:
        """Return the sampled target before rate limiting."""
        return self._target_command

    def set_command(
        self, command: torch.Tensor, env_ids: Sequence[int] | None = None
    ) -> None:
        """Set a fixed finite command for deterministic validation rollouts."""
        if env_ids is None:
            env_ids = slice(None)
            expected_rows = self.num_envs
        else:
            expected_rows = len(env_ids)
        if command.shape != (expected_rows, LOCOMOTION_COMMAND_DIM):
            raise ValueError(
                f"Expected command shape ({expected_rows}, {LOCOMOTION_COMMAND_DIM}), received {tuple(command.shape)}."
            )
        if not bool(torch.isfinite(command).all()):
            raise ValueError("Validation commands must contain only finite values.")
        if bool((command[:, BODY_HEIGHT] <= 0.0).any()):
            raise ValueError(
                "Validation body-height commands must be strictly positive."
            )
        self._target_command[env_ids] = command.to(self.device)
        self._command[env_ids] = command.to(self.device)

    def reset(self, env_ids: Sequence[int] | None = None) -> dict[str, float]:
        if env_ids is None:
            env_ids = slice(None)
        extras = super().reset(env_ids)
        self._command[env_ids] = self._target_command[env_ids]
        return extras

    def _resample_command(self, env_ids: Sequence[int]) -> None:
        sample = torch.empty(len(env_ids), device=self.device)
        ranges = self.cfg.ranges
        self._target_command[env_ids, FORWARD] = sample.uniform_(
            *ranges.forward_velocity_mps
        )
        self._target_command[env_ids, LATERAL] = sample.uniform_(
            *ranges.lateral_velocity_mps
        )
        self._target_command[env_ids, YAW_RATE] = sample.uniform_(
            *ranges.yaw_rate_radps
        )
        self._target_command[env_ids, BODY_HEIGHT] = sample.uniform_(
            *ranges.body_height_m
        )

    def _update_command(self) -> None:
        max_delta = self._max_rate * float(self._env.step_dt)
        delta = torch.clamp(
            self._target_command - self._command, min=-max_delta, max=max_delta
        )
        self._command.add_(delta)

    def _update_metrics(self) -> None:
        pass

    def _validate_cfg(self) -> None:
        for name, bounds in vars(self.cfg.ranges).items():
            if name.startswith("_"):
                continue
            if len(bounds) != 2 or not all(math.isfinite(value) for value in bounds):
                raise ValueError(
                    f"Command range {name!r} must contain two finite values, received {bounds}."
                )
            if bounds[0] > bounds[1]:
                raise ValueError(
                    f"Command range {name!r} must be ordered, received {bounds}."
                )
        if self.cfg.ranges.body_height_m[0] <= 0.0:
            raise ValueError("Body-height commands must be strictly positive.")
        if len(self.cfg.max_rate) != LOCOMOTION_COMMAND_DIM or not all(
            math.isfinite(value) and value > 0.0 for value in self.cfg.max_rate
        ):
            raise ValueError(
                f"max_rate must contain {LOCOMOTION_COMMAND_DIM} finite positive values."
            )


@configclass
class LocomotionCommandCfg(CommandTermCfg):
    """Configuration for the deployable four-dimensional locomotion command."""

    class_type: type[CommandTerm] = LocomotionCommand
    resampling_time_range: tuple[float, float] = (10.0, 10.0)
    max_rate: tuple[float, float, float, float] = (0.5, 0.5, 0.5, 0.02)

    @configclass
    class Ranges:
        forward_velocity_mps: tuple[float, float] = (0.25, 0.45)
        lateral_velocity_mps: tuple[float, float] = (-0.10, 0.10)
        yaw_rate_radps: tuple[float, float] = (-0.25, 0.25)
        body_height_m: tuple[float, float] = (0.105, 0.105)

    ranges: Ranges = Ranges()


def locomotion_command(
    env, command_name: str = LOCOMOTION_COMMAND_NAME
) -> torch.Tensor:
    """Expose the shaped command as a named policy observation term."""
    command = env.command_manager.get_command(command_name)
    if command.shape[-1] != LOCOMOTION_COMMAND_DIM:
        raise RuntimeError(
            f"Expected locomotion commands with shape (..., {LOCOMOTION_COMMAND_DIM}), received {tuple(command.shape)}."
        )
    return command
