extends: ../main/b0_t1_ppo.yaml

protocol_version: E0-v1-P1-history
actor_observation_dim: 184
task: Base-Locomotion-Stackforce-Quadrupedal-History-v0

agent:
  run_name: p1_history_t1_foundation_seed${env.seed}

wandb:
  group: e0-p1-history-t1
