extends: ../main/b0_t1_ppo.yaml

protocol_version: E0-v1-P3-history-terrain
actor_observation_dim: 304
task: Base-Locomotion-Stackforce-Quadrupedal-History-Terrain-v0

agent:
  run_name: p3_history_terrain_t1_foundation_seed${env.seed}

wandb:
  group: e0-p3-history-terrain-t1
